// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiyzzosxsljdjboxlnkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpeXp6b3N4c2xqZGpib3hsbmtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDE0MjgsImV4cCI6MjA2MDU3NzQyOH0.6o0HfHfgVvMQmfiWabgpj-RSJY5MnhUWRa6Y2bxAink";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);